import Hero from "@/components/Hero";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hotel Mariador Park</title>
        <meta name="description" content="Generated by kanjī."></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero
        heading="Hotel Mariador Park"
        message="Adoptez les traditions sereines au coeur de Hotel Mariador Park."
      />
    </div>
  );
}
